name: Gerar EXE

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Instalar dependências
      run: pip install requests PySimpleGUI

    - name: Instalar PyInstaller
      run: pip install pyinstaller==5.13.2

    - name: Gerar executável
      run: pyinstaller --onefile --noconsole --icon=gps.ico --hidden-import PySimpleGUI gps_atual3.py

    - name: Salvar executável
      uses: actions/upload-artifact@v4
      with:
        name: programa
        path: dist/*.exe
